### PR TITLE
add a nvmrc

### PR DESCRIPTION
**Pull request by dawehner**
Everytime I try to work on this project my current node version is potentially wrong.
NVM solves this problem by managing your node versions

Note: This is useful, even beside of https://github.com/jsdrupal/drupal-admin-ui/pull/580 for things like `audit, add` etc. People might run them outside of the container.

### CODE REVIEW

**Comment by justafish** [comment]
@dawehner yarn already throws an error if you try to run anything with the wrong version of node, is this not happening for you?

**Comment by justafish** [comment]
which is taken from https://github.com/jsdrupal/drupal-admin-ui/blob/master/package.json#L8

**Comment by dawehner** [comment]
@justafish Well that's the point, with a nvmrc in place you don't need to get the error in the first place.

**Comment by dawehner** [comment]
Well, other's seems to not have these problems ¯\_(ツ)_/¯

**Pull request closed without merging**
