### PR TITLE
Improve reporting of  a11y issues [lint checks and react-axe ] ( #109 )

### PR DESCRIPTION
**Pull request by martinfrances107**
## Issue

https://github.com/jsdrupal/drupal-admin-ui/issues/109

## Screenshot / UI changes

Describe the UI changes / make a screenshot

## Testing instructions

Using Chrome's devtools accessibility errors are highlights in the console window

Please describe with a few words how to reproduce the problem / test the feature

A DX improvement to produce early failure, in regard to a11y.

### CODE REVIEW

**Comment by martinfrances107** [comment]
Here is a screenshot showing axe's helpful warning 

react-axe

**Comment by dawehner** [comment]
Is there a way to automate some of those failures, so nightwatch catch them?

**Comment by martinfrances107** [comment]
> Is there a way to automate some of those failures,


@mgifford has provided the answer ( see the issue ) 

inshort -- if set set the ruleset to "strict" we can trigger errors while linting.

**Comment by martinfrances107** [comment]
I need to explain the latest push to the PR
 
🎉 It is all change Monday, 
 The random failure has been resolved, 
  The dbLog page is no longer 404'ing.

So here I can fix the onChange for onBlur in the places highlighted by the test errors.

Thank you all....

**Comment by lauriii** [comment]
We currently have some failures but after these gets resolved, it would be great if our CI could somehow test these as well.

**Comment by martinfrances107** [comment]
> it would be great if our CI could somehow test these as well.

@lauriii 

Can I pin this issue to  ( #109 ) 

Referring to one of my comments ...  I am advocating  that all the messy failures are dumped into console pane as the  developer works - Once our technical debt is fixed they maybe we should go for "strict" over "recommended"   as we set the ruleset

**Pull request merged**
