### PR TITLE
We now need at least PHP 7.1.  We need the php-gd extension too.

### PR DESCRIPTION
**Pull request by progga**
I have updated the README file to clarify the current PHP requirements to run the drupal-admin-ui *demo* Drupal site.

## Issue

https://github.com/jsdrupal/drupal-admin-ui/issues/317

## Screenshot / UI changes

N/A

## Testing instructions

N/A

### CODE REVIEW

**Comment by progga** [comment]
Hi Matt,
When installing Drupal with a fresh PHP install, php-gd is usually the first one that breaks the Drupal installation process.  Drupal, of course, demands a few other [PHP extensions in its composer.json file](https://github.com/drupal/core/blob/d4565f6bd221244a22698f6e500f4ebf4f294d1a/composer.json#L6), but the rest are usually present in PHP environments.  That's why I have specifically mentioned *gd*.

This pull request may not be needed eventually.  But thanks for looking into it anyway.

**Comment by progga** [comment]
Ideally, the first item in the *Requirements* section of the README should be a pointer to [Drupal's PHP requirements](https://www.drupal.org/docs/8/system-requirements/php-requirements) page.  Just a thought :)

**Comment by dawehner** [comment]
@mattgrill Maybe it would be nice to post your thoughts on https://github.com/jsdrupal/drupal-admin-ui/issues/317

**Comment by dawehner** [comment]
@progga Should we close this pull request and replace it by one which restricts the PHP version to 7.0?

**Comment by progga** [comment]
> Should we close this pull request

Sure

**Pull request closed without merging**
