### PR TITLE
[WIP][#52] Add Nightwatch for functional browser tests, plus a test for th…

### PR DESCRIPTION
**Pull request by justafish**
…e Menu
#52 
Todo:
- [ ] Documentation
- [ ] Get this running in CircleCI

### CODE REVIEW

**Comment by dawehner** [comment]
@justafish Do you plan to hook this up with circleCI?

**Comment by justafish** [comment]
@dawehner I do, but if someone else wants to give it a go before I get to it then ping me in #javascript on Drupal Slack :+1:

**Comment by dawehner** [comment]
I do have one question right now though. This tests the app outside of Drupal. I am wondering whether that's the right thing to do. Should we maybe test the app being part of Drupal, aka. symlinked in? This way we might catch some bugs we otherwise would miss?

Once we say that we should test the app inside Drupal, couldn't we use the existing nightwatch setup?

**Comment by justafish** [comment]
Closed for #170

**Pull request closed without merging**
