### PR TITLE
Fix flaky nightwatch tests.

### PR DESCRIPTION
**Pull request by mattgrill**
## Issue

https://github.com/jsdrupal/drupal-admin-ui/issues/487

### CODE REVIEW

**Comment by dawehner** [comment]
Sadly it still fails :|

**Comment by mattgrill** [comment]
@dawehner Now it passes.

**Comment by dawehner** [comment]
It feels like it would be nicer to use an ID for the data-nightwatch attribute, but ¯\_(ツ)_/¯

**Pull request merged**
