### PR TITLE
Reanimate Storybook #630

### PR DESCRIPTION
**Pull request by martinfrances107**
## Issue

https://github.com/jsdrupal/drupal-admin-ui/issues/630

## Testing instructions

uncomment the storybook container in docker-compse.yml

Then 

make build
make up

visit http://localhost:9001

currently the storybook definitions needs updating, and so as storybook starts one sees a error listed below.

 This issue is just to get the docker container up and functioning 

```
exports is not defined
    ReferenceError: exports is not defined
    at Module../src/components/02_atoms/FileUpload/FileUpload.js (http://localhost:9001/main.42ade1d2e6828f0466f6.bundle.js:91:23)
    at __webpack_require__ (http://localhost:9001/runtime~main.42ade1d2e6828f0466f6.bundle.js:783:30)
    at fn (http://localhost:9001/runtime~main.42ade1d2e6828f0466f6.bundle.js:151:20)
    at Module.<anonymous> (http://localhost:9001/main.42ade1d2e6828f0466f6.bundle.js:574:19)
    at Module../src/components/02_atoms/FileUpload/FileUpload.stories.js (http://localhost:9001/main.42ade1d2e6828f0466f6.bundle.js:610:30)
    at __webpack_require__ (http://localhost:9001/runtime~main.42ade1d2e6828f0466f6.bundle.js:783:30)
    at fn (http://localhost:9001/runtime~main.42ade1d2e6828f0466f6.bundle.js:151:20)
    at webpackContext (http://localhost:9001/main.42ade1d2e6828f0466f6.bundle.js:21:9)
    at http://localhost:9001/main.42ade1d2e6828f0466f6.bundle.js:70:12
    at Array.forEach (<anonymous>)


```

### CODE REVIEW

**Comment by martinfrances107** [comment]
The reason for test failure:

I did not correctly adjust all uses of the .drupal-build-complete flag.

**Comment by iberdinsky-skilld** [comment]
storybook works for me with small fix from https://github.com/jsdrupal/drupal-admin-ui/issues/632#issuecomment-459645865

**Comment by dawehner** [comment]
@justafish moved the dev environment to be local node again, which means storybook is no longer an issue.

**Comment by dawehner** [comment]
Thanks a ton trying to fix it

**Pull request closed without merging**
