### PR TITLE
Add route override for entity.node.edit_form

### PR DESCRIPTION
**Pull request by alexburrows**
## Issue

https://github.com/jsdrupal/drupal-admin-ui/issues/493

## Screenshot / UI changes

When editing node from node view it now routes to correct vfancy route

## Testing instructions

View an existing node and then click edit, it will take you to the Drupal 8.x node edit form. Then apply pull request and it will redirect to vfancy entity.edit_form

### CODE REVIEW

**Comment by alexburrows** [comment]
Working on this

**Comment by dawehner** [comment]
Nice, thank you!

**Comment by dawehner** [comment]
I added some tests in https://github.com/jsdrupal/drupal-admin-ui/pull/536

**Comment by dawehner** [comment]
Note: https://github.com/jsdrupal/drupal-admin-ui/pull/536 but it also contains some test. Thanks for your fix @alexburrows !

**Pull request closed without merging**
