### PR TITLE
NodeForm initialisation generates warnings(#319)

### PR DESCRIPTION
**Pull request by martinfrances107**
## Issue

https://github.com/jsdrupal/drupal-admin-ui/issues/319

Please describe with a few words how to reproduce the problem / test the feature

Visit 

http://localhost:3000/node/add/recipe

open Chrome's dev tools .. look at the console log..

before the PR there was a NodeForm: initialization warning

after the PR the warning is resolved.

### CODE REVIEW

**Comment by martinfrances107** [comment]
> I think we can just do state = {}; and avoid the constructor function.

This does not work unfortunately.

I think the problem  is some poorly documented interaction when a class has a getDerivedStateFromProps() method.

This is what fails.

```
 static defaultProps = {
    schema: false,
    uiSchema: false,
  };

  static state = {};

  static getDerivedStateFromProps(props, prevState) {
    if (!props.schema) {
      return prevState;
    }
```

**Comment by mattgrill** [comment]
So I did just test this, 

state

**Comment by mattgrill** [comment]
Oh, I also see what happened. `static state = {}` is probably not what you want. CRA is probably using, https://babeljs.io/docs/en/next/babel-plugin-proposal-class-properties.html underneath.

**Comment by martinfrances107** [comment]
Oh dear god..  what was I thinking.

I haven't made a mistake that big since I wandered around nursery school without any trousers on!

**Pull request merged**
